added solution for 08-authentication 01-local task
js-tasks-ru/nodejs-20200728_artem-lapkin pull request #10
Opened 2020-10-26 15:29 UTC by crappydeveloper

2020-10-26 16:29 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Настройка локальной стратегии
+ поле usernameField должно должно содержать email
+ стратегия должна возвращать ошибку если указан несуществующи�� email
+ стратегия должна возвращать ошибку если указан неверный пароль
+ стратегия должна возвращать объект пользователя если email и пароль верные
```

Добавляю преподавателя (@tadjik1) для код-ревью, посмотрим что он скажет :)

2020-10-26 16:44 UTC, tadjik1 commented on 08-authentication/01-local/libs/strategies/local.js
> +  async function(email, password, done) {
каждый раз когда мы объявляем async функцию - создаётся промис, ошибки из которого обрабатывются самой nodejs. т.к. в данном случае наша функция выполняется не в контексте koajs возможна ситуация, что при ошибке она будет либо проигнорирована и запрос подвиснет (версии nodejs < 15), либо процесс вылетит с этой ошибкой вовсе (>15).
конечно, и то, и другое нас не устраивает, поэтому надо обязательно добавить `try/catch` здесь для обработки ошибок.

2020-10-26 16:44 UTC, tadjik1 requested changes
@crappydeveloper хороший код и верное решение. надо лишь исправить небольшой комментарий

2020-10-27 08:01 UTC, crappydeveloper commented on 08-authentication/01-local/libs/strategies/local.js
> +  async function(email, password, done) {
Готово. Теперь должно быть корректно

Спасибо большое за "хороший код", а за замечание двойное спасибо

2020-10-27 08:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2020-10-27 08:30 UTC, tadjik1 approved these changes
Теперь все отлично 👏

2020-10-27 08:31 UTC, merged